// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Navigation → Links*
 */
export interface NavigationDocumentDataLinksItem {
  /**
   * Label field in *Navigation → Links*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Optional - Label for the link
   * - **API ID Path**: navigation.links[].label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.TitleField;

  /**
   * Link field in *Navigation → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for navigation item
   * - **API ID Path**: navigation.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Links field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<NavigationDocumentDataLinksItem>>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | PromoBannerSlice
  | HeroSlice
  | SubscriptionsCarrouselSlice
  | AvantagesSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Parent field in *Page*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: page.parent
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  parent: prismic.ContentRelationshipField<"page">;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type ProductDocumentDataSlicesSlice =
  | PromoBannerSlice
  | HeroSlice
  | SubscriptionsCarrouselSlice
  | AvantagesSlice;

/**
 * Content for Product documents
 */
interface ProductDocumentData {
  /**
   * Product name field in *Product*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.product_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  product_name: prismic.RichTextField;

  /**
   * PIM mapping field in *Product*
   *
   * - **Field Type**: Integration Fields (Catalog: `bimandgo-demo--telepeage_pim`)
   * - **Placeholder**: Pick a product in the catalog
   * - **API ID Path**: product.pim_mapping
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  pim_mapping: prismic.IntegrationField;

  /**
   * Slice Zone field in *Product*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: product.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProductDocumentDataSlicesSlice> /**
   * Meta Description field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: product.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Product*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: product.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Product document from Prismic
 *
 * - **API ID**: `product`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProductDocumentData>,
    "product",
    Lang
  >;

/**
 * Item in *Promo coupons → Coupons*
 */
export interface PromoCouponsDocumentDataCouponsItem {
  /**
   * identifier field in *Promo coupons → Coupons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: promo_coupons.coupons[].identifier
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  identifier: prismic.KeyTextField;

  /**
   * coupon code field in *Promo coupons → Coupons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: promo_coupons.coupons[].coupon_code
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  coupon_code: prismic.KeyTextField;

  /**
   * validity start field in *Promo coupons → Coupons*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: promo_coupons.coupons[].validity_start
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  validity_start: prismic.DateField;

  /**
   * validity end field in *Promo coupons → Coupons*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: promo_coupons.coupons[].validity_end
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  validity_end: prismic.DateField;

  /**
   * discount field in *Promo coupons → Coupons*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: promo_coupons.coupons[].discount
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  discount: prismic.NumberField;
}

/**
 * Content for Promo coupons documents
 */
interface PromoCouponsDocumentData {
  /**
   * Coupons field in *Promo coupons*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: promo_coupons.coupons[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  coupons: prismic.GroupField<Simplify<PromoCouponsDocumentDataCouponsItem>>;
}

/**
 * Promo coupons document from Prismic
 *
 * - **API ID**: `promo_coupons`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PromoCouponsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PromoCouponsDocumentData>,
    "promo_coupons",
    Lang
  >;

/**
 * Item in *Redirections → Redirections*
 */
export interface RedirectionsDocumentDataRedirectionsItem {
  /**
   * type field in *Redirections → Redirections*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 301
   * - **API ID Path**: redirections.redirections[].type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<"301" | "302", "filled">;

  /**
   * old url field in *Redirections → Redirections*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: redirections.redirections[].old_url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  old_url: prismic.KeyTextField;

  /**
   * new url field in *Redirections → Redirections*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: redirections.redirections[].new_url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  new_url: prismic.KeyTextField;
}

/**
 * Content for Redirections documents
 */
interface RedirectionsDocumentData {
  /**
   * Redirections field in *Redirections*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: redirections.redirections[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  redirections: prismic.GroupField<
    Simplify<RedirectionsDocumentDataRedirectionsItem>
  >;

  /**
   * Hello field in *Redirections*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: redirections.hello
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hello: prismic.KeyTextField;
}

/**
 * Redirections document from Prismic
 *
 * - **API ID**: `redirections`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RedirectionsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<RedirectionsDocumentData>,
    "redirections",
    Lang
  >;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title of the site
   * - **API ID Path**: settings.siteTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  siteTitle: prismic.TitleField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | NavigationDocument
  | PageDocument
  | ProductDocument
  | PromoCouponsDocument
  | RedirectionsDocument
  | SettingsDocument;

/**
 * Item in *Avantages → Default → Primary → Avantages*
 */
export interface AvantagesSliceDefaultPrimaryAvantagesItem {
  /**
   * Icon field in *Avantages → Default → Primary → Avantages*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: avantages.default.primary.avantages[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *Avantages → Default → Primary → Avantages*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: avantages.default.primary.avantages[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *Avantages → Default → Primary → Avantages*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: avantages.default.primary.avantages[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *Avantages → Default → Primary*
 */
export interface AvantagesSliceDefaultPrimary {
  /**
   * Titre field in *Avantages → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: avantages.default.primary.titre
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titre: prismic.RichTextField;

  /**
   * Image field in *Avantages → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: avantages.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Avantages field in *Avantages → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: avantages.default.primary.avantages[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  avantages: prismic.GroupField<
    Simplify<AvantagesSliceDefaultPrimaryAvantagesItem>
  >;
}

/**
 * Default variation for Avantages Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AvantagesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AvantagesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Avantages*
 */
type AvantagesSliceVariation = AvantagesSliceDefault;

/**
 * Avantages Shared Slice
 *
 * - **API ID**: `avantages`
 * - **Description**: Avantages
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AvantagesSlice = prismic.SharedSlice<
  "avantages",
  AvantagesSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Checks field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.checks
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  checks: prismic.RichTextField;

  /**
   * Button field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  button: prismic.RichTextField;

  /**
   * Button2 field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  button2: prismic.RichTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *PromoBanner → Default → Primary*
 */
export interface PromoBannerSliceDefaultPrimary {
  /**
   * Image field in *PromoBanner → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: promo_banner.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Text field in *PromoBanner → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: promo_banner.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Button field in *PromoBanner → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: promo_banner.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  button: prismic.RichTextField;
}

/**
 * Default variation for PromoBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PromoBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PromoBannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PromoBanner*
 */
type PromoBannerSliceVariation = PromoBannerSliceDefault;

/**
 * PromoBanner Shared Slice
 *
 * - **API ID**: `promo_banner`
 * - **Description**: PromoBanner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PromoBannerSlice = prismic.SharedSlice<
  "promo_banner",
  PromoBannerSliceVariation
>;

/**
 * Item in *SubscriptionsCarrousel → Default → Primary → Tab*
 */
export interface SubscriptionsCarrouselSliceDefaultPrimaryTabItem {
  /**
   * Tab label field in *SubscriptionsCarrousel → Default → Primary → Tab*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subscriptions_carrousel.default.primary.tab[].tab_label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  tab_label: prismic.RichTextField;

  /**
   * Countries field in *SubscriptionsCarrousel → Default → Primary → Tab*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subscriptions_carrousel.default.primary.tab[].countries
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  countries: prismic.RichTextField;
}

/**
 * Primary content in *SubscriptionsCarrousel → Default → Primary*
 */
export interface SubscriptionsCarrouselSliceDefaultPrimary {
  /**
   * Title field in *SubscriptionsCarrousel → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subscriptions_carrousel.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *SubscriptionsCarrousel → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subscriptions_carrousel.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * Tab field in *SubscriptionsCarrousel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: subscriptions_carrousel.default.primary.tab[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  tab: prismic.GroupField<
    Simplify<SubscriptionsCarrouselSliceDefaultPrimaryTabItem>
  >;
}

/**
 * Default variation for SubscriptionsCarrousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SubscriptionsCarrouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SubscriptionsCarrouselSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SubscriptionsCarrousel*
 */
type SubscriptionsCarrouselSliceVariation = SubscriptionsCarrouselSliceDefault;

/**
 * SubscriptionsCarrousel Shared Slice
 *
 * - **API ID**: `subscriptions_carrousel`
 * - **Description**: SubscriptionsCarrousel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SubscriptionsCarrouselSlice = prismic.SharedSlice<
  "subscriptions_carrousel",
  SubscriptionsCarrouselSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataLinksItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ProductDocument,
      ProductDocumentData,
      ProductDocumentDataSlicesSlice,
      PromoCouponsDocument,
      PromoCouponsDocumentData,
      PromoCouponsDocumentDataCouponsItem,
      RedirectionsDocument,
      RedirectionsDocumentData,
      RedirectionsDocumentDataRedirectionsItem,
      SettingsDocument,
      SettingsDocumentData,
      AllDocumentTypes,
      AvantagesSlice,
      AvantagesSliceDefaultPrimaryAvantagesItem,
      AvantagesSliceDefaultPrimary,
      AvantagesSliceVariation,
      AvantagesSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      PromoBannerSlice,
      PromoBannerSliceDefaultPrimary,
      PromoBannerSliceVariation,
      PromoBannerSliceDefault,
      SubscriptionsCarrouselSlice,
      SubscriptionsCarrouselSliceDefaultPrimaryTabItem,
      SubscriptionsCarrouselSliceDefaultPrimary,
      SubscriptionsCarrouselSliceVariation,
      SubscriptionsCarrouselSliceDefault,
    };
  }
}
