// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  avantages: dynamic(() => import("./Avantages")),
  hero: dynamic(() => import("./Hero")),
  promo_banner: dynamic(() => import("./PromoBanner")),
  subscriptions_carrousel: dynamic(() => import("./SubscriptionsCarrousel")),
};
